CREATE DATABASE bookedup_db;


-- run server before using and inserting into the db
-- sequelize code in the models folder needs to run and create the table structure first

USE bookedup_db;


INSERT INTO books (title, author, genre, year_published, rating, synopsis, cover, createdAt, updatedAt)
VALUES ('Harry Potter and the Order of the Phoenix', 'J.K. Rowling', 'fantasy', 2003, 10.0, "Dark times have come to Hogwarts. After the Dementors' attack on his cousin Dudley, Harry Potter knows that Voldemort will stop at nothing to find him. There are many who deny the Dark Lord's return, but Harry is not alone: a secret order gathers at Grimmauld Place to fight against the Dark forces. Harry must allow Professor Snape to teach him how to protect himself from Voldemort's savage assaults on his mind. But they are growing stronger by the day and Harry is running out of time...", 'https://www.scholastic.com/content5/media/products/71/9780439358071_mres.jpg', '2019-05-18 17:42:17', '2019-05-18 17:42:17'), 
('Becoming Beyoncé', 'J. Randy Taraborrelli', 'biographical', 2015, 9.0, "Beyoncé Knowles is a woman who began her career at the age of eight performing in pageant shows and talent contests, honing her craft through her teenage years until, at the age of 16, she had her first number one record with Destiny's Child. That hit-making trio launched Beyoncé's successful solo career, catapulting her, as of 2014, to #1 on Forbes annual list of most wealthy celebrities--the same year she made the cover of Time. BECOMING BEYONCÉ is not only the story of struggle, sacrifice, and what it takes to make it in the cut-throat record industry, it's the story of the great rewards of such success and the devastating toll it often takes on the human spirit.", 'https://books.google.com/books/content?id=CmeWBgAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&imgtk=AFLRE71UdGguDn_WEBUGrX57O0k8gOETw3yMKAt5j7BnziSSWVDTPQiHe6bxyTmLx-ulvyLFjlzDlXJkR2c02AKLc7xCf5WEonE9BF9wJasVYOMdO8z4lkjfWx5Q9szKv8UbdvKfyT_I', '2019-05-18 17:42:17', '2019-05-18 17:42:17'),
('The Magicians', 'Lev Grossman', 'fantasy', 2011, 9.2, "Like everyone else, precocious high school senior Quentin Coldwater assumes that magic isn't real, until he finds himself admitted to a very secretive and exclusive college of magic in upstate New York. There he indulges in joys of college-friendship, love, sex, and booze- and receives a rigorous education in modern sorcery.", 'https://books.google.com/books/content?id=eaZSYAAACAAJ&printsec=frontcover&img=1&zoom=1&imgtk=AFLRE70N3i-KCEnSv_HxfKfZZDsIMSNUKVlVkBcdoJ75sDRvRxFdeds3dMsDKICV6swKrIDzmp7IYTJqDwv5I3rj1w89gEseQYj5a2eAuJ1e5isnGHgpLnGUO32sYQbMEJG8s8M7KU1L', '2019-05-18 17:42:17', '2019-05-18 17:42:17'),
('1984', 'George Orwell', 'dystopian,political-fiction', 1983, 9.1, "In 1984, London is a grim city in the totalitarian state of Oceania where Big Brother is always watching you and the Thought Police can practically read your mind. Winston Smith is a man in grave danger for the simple reason that his memory still functions. Drawn into a forbidden love affair, Winston finds the courage to join a secret revolutionary organization called The Brotherhood, dedicated to the destruction of the Party. Together with his beloved Julia, he hazards his life in a deadly match against the powers that be.", 'https://books.google.com/books/content?id=kotPYEqx7kMC&printsec=frontcover&img=1&zoom=1&edge=curl&imgtk=AFLRE73WtuadcMZpQ8U60FDNPNE7t2uRaXVTeFatWkHOo9SgHxZdkWhXkgpXMg_xoss47P_5jrEQttQtPwWnUrk3rq_wWaLgbfzPB0G5gKiwCxTVaWvQ1tXaUdd6trRdC4JkJuEsg-IW', '2019-05-18 17:42:17', '2019-05-18 17:42:17'),
('A Game of Thrones', 'George R.R. Martin', 'epic-fantasy', 1996, 10.0, "Winter is coming. Such is the stern motto of House Stark, the northernmost of the fiefdoms that owe allegiance to King Robert Baratheon in far-off King’s Landing. There Eddard Stark of Winterfell rules in Robert’s name. There his family dwells in peace and comfort: his proud wife, Catelyn; his sons Robb, Brandon, and Rickon; his daughters Sansa and Arya; and his bastard son, Jon Snow. Far to the north, behind the towering Wall, lie savage Wildings and worse—unnatural things relegated to myth during the centuries-long summer, but proving all too real and all too deadly in the turning of the season.", 'https://books.google.com/books/content?id=5NomkK4EV68C&printsec=frontcover&img=1&zoom=1&edge=curl&imgtk=AFLRE72IfXiuko16u7ZbPCXOSKXaEIBE3uw_O8Uso1R0f0JGXUWkwbVGEdAJprhClZXMLyLcZ5nIOwgaDoRwo5bMmDzO2aPGVWCf5RG9E4Bp-nm2JHgdpakuBj-wY_HuRALGASxIHKck', '2019-05-18 17:42:17', '2019-05-18 17:42:17'),
('The Catcher in the Rye', 'J.D. Salinger', 'realistic-fiction', 1951, 9.5, "Through circumstances that tend to preclude adult, secondhand description, he leaves his prep school in Pennsylvania and goes underground in New York City for three days. The boy himself is at once too simple and too complex for us to make any final comment about him or his story. Perhaps the safest thing we can say about Holden is that he was born in the world not just strongly attracted to beauty but, almost, hopelessly impaled on it.", 'https://books.google.com/books/content?id=Bb91ngEACAAJ&printsec=frontcover&img=1&zoom=1&imgtk=AFLRE712qPQ6yJE_NYvO-XvbUs24GA-ceGV7VJJdtCc6vKYVr-j6ov8PF-gkvNLOB5jBVtJc9bai20hCxkWLmC8kkvLjuj0yhwQos9wWP04hsOvD5TY_QbdZLEldd-BlcP1SJBgemfB6', '2019-05-18 17:42:17', '2019-05-18 17:42:17'),
('And Then There Were None', 'Agatha Christie', 'fiction,mystery', 1939, 8.7, "Ten people, each with something to hide and something to fear, are invited to a isolated mansion on Indian Island by a host who, surprisingly, fails to appear. On the island they are cut off from everything but each other and the inescapable shadows of their own past lives. One by one, the guests share the darkest secrets of their wicked pasts. And one by one, they die…", 'https://books.google.com/books/content?id=ACMYLqk_7GoC&printsec=frontcover&img=1&zoom=1&edge=curl&imgtk=AFLRE70dFsWwK6KF4sLle9sLtCX6z-daLTSgqE9u8zBhBKxNrDm4w0oD23dMps4J7ehSxOwOKCA8uAE0513M3achZBRho1qA9-Gj-dcN0gNeymz_NMsdVgQjagYj-naNYPABd23XGo0C', '2019-05-18 17:42:17', '2019-05-18 17:42:17'),
('Fifty Shades of Grey', 'E.L. James', 'erotic-romance', 2011, 8.0, "When literature student Anastasia Steele goes to interview young entrepreneur Christian Grey, she encounters a man who is beautiful, brilliant, and intimidating. The unworldly, innocent Ana is startled to realize she wants this man and, despite his enigmatic reserve, finds she is desperate to get close to him. Unable to resist Ana's quiet beauty, wit, and independent spirit, Grey admits he wants her, too--but on his own terms.", 'https://books.google.com/books/content?id=GbVdlAEACAAJ&printsec=frontcover&img=1&zoom=1&imgtk=AFLRE72gXiFionCCpXKg3xyxN0z32Yy3HlInp2k5wQBWRq8vAJ-tkCaTojnAVAzkzP3hBtOwV2C0Xjz_qrPs3GdT4uVLbtEdIjvlQsUESzzw9sJqnlroq54-SQpMAe3nSxl-b-VD-JVP', '2019-05-18 17:42:17', '2019-05-18 17:42:17'),
('Diary of a Wimpy Kid', 'Jeff Kinney', 'fiction', 2007, 7.9, "Greg Heffley finds himself thrust into a new year and a new school where undersize weaklings share the corridors with kids who are taller, meaner and already shaving.Desperate to prove his new found maturity, which only going up a grade can bring, Greg is happy to have his not-quite-so-cool sidekick, Rowley, along for the ride. But when Rowley's star starts to rise, Greg tries to use his best friend's popularity to his own advantage.", 'https://books.google.com/books/content?id=JAWwjgEACAAJ&printsec=frontcover&img=1&zoom=1&imgtk=AFLRE71Lst0hcAS6qqXfmyoUAKQM2WPkbOQhzVIPJJFMCOGmxLCl9a38lfjHIJdBdv1RK03L9v1cHo2OknyV4WGHs5m37LmmyP8rhyB2CpVyt1EoucOYT6RlhJFxPI4viq9nQHd7d2BL', '2019-05-18 17:42:17', '2019-05-18 17:42:17');
